### ISSUE TITLE
Item frames still rendered even with rendering distance turned to 0.

### ISSUE THREAD

**Issue by respectablenoob-source** [capnkork/entity-distance#3]

**Comment by capnkork** [comment]
I'll have to look into this. I'm pretty sure there are other entities that also don't work correct (probably all block/tile entities).

**Comment by capnkork** [comment]
This is now fixed for item frames and glow item frames. There are probably still other entities that don't work currently, but I will address those at another time.

Note: Due to how Minecraft handles item frames in the code, you may have to turn render distance very low to see an effect.
