### ISSUE TITLE
Config for mod won't generate.

### ISSUE THREAD

**Issue by Kichura** [capnkork/entity-distance#4]
When using this mod, It tries to generate a config but fails to do so and instead comes with an consistent error message saying the json file could not be found.

but manually creating the "entitydistancemod.json" and setting the text to `{}` causes the message to be suppressed.

**Comment by capnkork** [comment]
That message is more of a warning than an error. If no config is found, it just uses default values. However, it doesn't actually create a config file until you change the distance of an entity save (which may be considered a bug or undesired behavior).

Does a config file get generated when changing the distance for an entity and clicking save?

**Comment by Kichura** [comment]
When i tried to manually adjust the entity distance directly from the video settings itself; the config does not appear,

But adjusting it directly with mod menu, the config will become modified. (however fails to give a proper clue on how to use the config itself)

**Comment by capnkork** [comment]
This seems like correct behavior. If you're looking to manually edit the config file directly, that's not something I really planned for users to do (but is totally possible if done while the game isn't running and you get the format correct).

As far as proper usage on the mod itself, the readme could use some instruction. I will probably make a separate issue for that.
